"""empty message

Revision ID: 4223eba9a854
Revises: 2940356ebeac
Create Date: 2020-06-29 08:48:01.764772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4223eba9a854'
down_revision = '2940356ebeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_1', sa.Integer(), nullable=True),
    sa.Column('usuario_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_contacto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_emisor', sa.Integer(), nullable=True),
    sa.Column('usuario_receptor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_contacto')
    op.drop_table('contacto')
    # ### end Alembic commands ###
