"""empty message

Revision ID: 6030eadd9681
Revises: 
Create Date: 2020-06-07 12:05:43.876177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6030eadd9681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video', sa.String(length=32), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('NO_ME_GUSTA', 'ME_GUSTA', name='tiporeaccion'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaccion')
    # ### end Alembic commands ###
