"""empty message

Revision ID: ffc2a1158712
Revises: ebaca45ba907
Create Date: 2020-07-30 00:37:05.730036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc2a1158712'
down_revision = 'ebaca45ba907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacto', 'fecha')
    # ### end Alembic commands ###
